//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.4.0-b180830.0438 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.30 at 01:37:15 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "www.assembly.gov.rs/pubs/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.scholarly.publishing.jaxb.models;
