//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.4.0-b180830.0438 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.30 at 01:37:15 PM CET 
//


package app.jaxb_model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the app.jaxb_model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: app.jaxb_model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Publication }
     * 
     */
    public Publication createPublication() {
        return new Publication();
    }

    /**
     * Create an instance of {@link Publication.References }
     * 
     */
    public Publication.References createPublicationReferences() {
        return new Publication.References();
    }

    /**
     * Create an instance of {@link Publication.Keywords }
     * 
     */
    public Publication.Keywords createPublicationKeywords() {
        return new Publication.Keywords();
    }

    /**
     * Create an instance of {@link Publication.Authors }
     * 
     */
    public Publication.Authors createPublicationAuthors() {
        return new Publication.Authors();
    }

    /**
     * Create an instance of {@link Publication.Abstract }
     * 
     */
    public Publication.Abstract createPublicationAbstract() {
        return new Publication.Abstract();
    }

    /**
     * Create an instance of {@link Publication.Content }
     * 
     */
    public Publication.Content createPublicationContent() {
        return new Publication.Content();
    }

    /**
     * Create an instance of {@link Author }
     * 
     */
    public Author createAuthor() {
        return new Author();
    }

    /**
     * Create an instance of {@link Section }
     * 
     */
    public Section createSection() {
        return new Section();
    }

    /**
     * Create an instance of {@link Paragraph }
     * 
     */
    public Paragraph createParagraph() {
        return new Paragraph();
    }

    /**
     * Create an instance of {@link List }
     * 
     */
    public List createList() {
        return new List();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link Publication.References.Reference }
     * 
     */
    public Publication.References.Reference createPublicationReferencesReference() {
        return new Publication.References.Reference();
    }

    /**
     * Create an instance of {@link Publication.Keywords.Word }
     * 
     */
    public Publication.Keywords.Word createPublicationKeywordsWord() {
        return new Publication.Keywords.Word();
    }

}
